server:
  port: ${PORT}

spring:
  flyway:
    locations: classpath:/db/migrations
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  token:
    value: ${TOKEN}