version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/openjdk:11-jdk
    working-directory: ~/repo
    steps: 
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
  deploy-staging: 
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Staging
          command: apt-get update -qy && gem install dpl && dpl --provider=heroku --app=$HEROKU_APP_NAME_STG --api-key=$HEROKU_API_KEY
  deploy-prod:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PRD.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
      - approve-deploy-prod:
          type: approval
          requires:
            - deploy-staging
      - deploy-prod:
          requires:
            - approve-deploy-prod