version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/openjdk:11-jdk
    working-directory: ~/repo
    steps: 
      - checkout
workflows:
  version: 2
  build-deploy:
    jobs:
      - build