version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/node:12.9.1-browsers
    working-directory: ~/repo
    steps: 
      - checkout
workflows:
  version: 2
  build-deploy:
    jobs:
      - build