version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
  deploy-staging:
    docker:
      - image: ruby
    steps:
      - checkout
      - run:
          name: Deploy to Staging
          command: |
            apt-get update -qy && apt-get install -y ruby-dev && gem install dpl && dpl --provider=heroku --app=$HEROKU_APP_NAME_STG --api-key=$HEROKU_API_KEY
  deploy-prod:
    docker:
      - image: ruby
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            apt-get update -qy && apt-get install -y ruby-dev && gem install dpl && dpl --provider=heroku --app=$HEROKU_APP_NAME_PRD --api-key=$HEROKU_API_KEY
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - approve-deploy-prod:
          type: approval
          requires:
            - deploy-staging
      - deploy-prod:
          requires:
            - approve-deploy-prod
